export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";

export const GET_BOOKS_REQUEST = "GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILURE = "GET_BOOKS_FAILURE";

export const GET_BOOK_REQUEST = "GET_BOOK_REQUEST";
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";
export const GET_BOOK_FAILURE = "GET_BOOK_FAILURE";

export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAILURE = "DELETE_BOOK_FAILURE";

export const ADD_BOOK_REQUEST = "ADD_BOOK_REQUEST";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAILURE = "ADD_BOOK_FAILURE";

export const EDIT_BOOK_REQUEST = "EDIT_BOOK_REQUEST";
export const EDIT_BOOK_SUCCESS = "EDIT_BOOK_SUCCESS";
export const EDIT_BOOK_FAILURE = "EDIT_BOOK_FAILURE";

export const GET_AUTHORS_REQUEST = "GET_AUTHORS_REQUEST";
export const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS";
export const GET_AUTHORS_FAILURE = "GET_AUTHORS_FAILURE";

export const GET_AUTHOR_REQUEST = "GET_AUTHOR_REQUEST";
export const GET_AUTHOR_SUCCESS = "GET_AUTHOR_SUCCESS";
export const GET_AUTHOR_FAILURE = "GET_AUTHOR_FAILURE";

export const EDIT_AUTHOR_REQUEST = "EDIT_AUTHOR_REQUEST";
export const EDIT_AUTHOR_SUCCESS = "EDIT_AUTHOR_SUCCESS";
export const EDIT_AUTHOR_FAILURE = "EDIT_AUTHOR_FAILURE";

export const ADD_AUTHOR_REQUEST = "ADD_AUTHOR_REQUEST";
export const ADD_AUTHOR_SUCCESS = "ADD_AUTHOR_SUCCESS";
export const ADD_AUTHOR_FAILURE = "ADD_AUTHOR_FAILURE";

export const DELETE_AUTHOR_REQUEST = "DELETE_AUTHOR_REQUEST";
export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";
export const DELETE_AUTHOR_FAILURE = "DELETE_AUTHOR_FAILURE";

export const ADD_AUTHORS_BOOK_REQUEST = "ADD_AUTHORS_BOOK_REQUEST";
export const ADD_AUTHORS_BOOK_SUCCESS = "ADD_AUTHORS_BOOK_SUCCESS";
export const ADD_AUTHORS_BOOK_FAILURE = "ADD_AUTHORS_BOOK_FAILURE";

export const DELETE_AUTHORS_BOOK_REQUEST = "DELETE_AUTHORS_BOOK_REQUEST";
export const DELETE_AUTHORS_BOOK_SUCCESS = "DELETE_AUTHORS_BOOK_SUCCESS";
export const DELETE_AUTHORS_BOOK_FAILURE = "DELETE_AUTHORS_BOOK_FAILURE";

export const ADD_BOOKS_AUTHOR_REQUEST = "ADD_BOOKS_AUTHOR_REQUEST";
export const ADD_BOOKS_AUTHOR_SUCCESS = "ADD_BOOKS_AUTHOR_SUCCESS";
export const ADD_BOOKS_AUTHOR_FAILURE = "ADD_BOOKS_AUTHOR_FAILURE";

export const DELETE_BOOKS_AUTHOR_REQUEST = "DELETE_BOOKS_AUTHOR_REQUEST";
export const DELETE_BOOKS_AUTHOR_SUCCESS = "DELETE_BOOKS_AUTHOR_SUCCESS";
export const DELETE_BOOKS_AUTHOR_FAILURE = "DELETE_BOOKS_AUTHOR_FAILURE";


